[[unixODBC]]
arch = "aarch64"
git-tree-sha1 = "b3d4097034cd48a0c6c5b0cf2342c9cff344df74"
os = "macos"

    [[unixODBC.download]]
    sha256 = "982274b7be0cafafe9041174636c8d15c33943fffa548a39cbad6ec8155d3575"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.aarch64-apple-darwin.tar.gz"
[[unixODBC]]
arch = "aarch64"
git-tree-sha1 = "99c1a0416421515bbcd8e9fb331d2bcf71c60d5a"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "1844d8e0090d5d2fe1a5213806db690c6dbd4c7b5c1ab85bea4fe0af59dbfe3c"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.aarch64-linux-gnu.tar.gz"
[[unixODBC]]
arch = "aarch64"
git-tree-sha1 = "5fd259ff214788e3d3cbc656606fdddf96e9c1b9"
libc = "musl"
os = "linux"

    [[unixODBC.download]]
    sha256 = "fc47b89a90a3ddb0362ad016ddfb70250c031fe12b7bdbb51b1c9286f49b1d3d"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.aarch64-linux-musl.tar.gz"
[[unixODBC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "30b3c0793f9a658f685500055c6200d7afe4f678"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "e82d4888415aa804283532dd017d05097197fe1493073fc3aa51648e7752b032"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.armv6l-linux-gnueabihf.tar.gz"
[[unixODBC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "09e48ea2b2ef58fadcda3255a7be0c3c74d625c0"
libc = "musl"
os = "linux"

    [[unixODBC.download]]
    sha256 = "d70348117b7d6a6e0cde33131bc409f6e6f22ca3173679ef070e168972445454"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.armv6l-linux-musleabihf.tar.gz"
[[unixODBC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "10929409cc2d5492ffbd8e0aece24af8e0aa7800"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "5454b6cf6807684cca5a6f628776925c125461c40332b489510106aab01f0654"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.armv7l-linux-gnueabihf.tar.gz"
[[unixODBC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c55473e26651865791134973f22a80166868f44a"
libc = "musl"
os = "linux"

    [[unixODBC.download]]
    sha256 = "f2e39ca1849d599cb57273f8f149aeaa2f50ab7e7e999f2efc628f25b9d89386"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.armv7l-linux-musleabihf.tar.gz"
[[unixODBC]]
arch = "i686"
git-tree-sha1 = "4289fef7b615b4d024decffb776e262b2a543d77"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "24f17126a1116eaea8e670ceed6512a3a5ce154f8c50a16b5beae09b1d817eb3"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.i686-linux-gnu.tar.gz"
[[unixODBC]]
arch = "i686"
git-tree-sha1 = "faed81a868569461d5d1941a761bba22dc14cd4b"
libc = "musl"
os = "linux"

    [[unixODBC.download]]
    sha256 = "c48297acc5df43d62a913509a05b623ce75aef5f30806a1145a5257e9809d67d"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.i686-linux-musl.tar.gz"
[[unixODBC]]
arch = "i686"
git-tree-sha1 = "50f0e2f9f21ccbcba932b8e0f1a35171bfba35cb"
os = "windows"

    [[unixODBC.download]]
    sha256 = "2ddecbe607b155f31c7332066469bf0a4ebef7d0ba3b90b13a1d758246b197a5"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.i686-w64-mingw32.tar.gz"
[[unixODBC]]
arch = "powerpc64le"
git-tree-sha1 = "5bd71bb32999b7e1551377d5d4920b45ce8cdd22"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "2a5f97fd8290007e1afefac82bd0f8c26f62736ee3edf131c8a6dbe1ffc0f50a"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.powerpc64le-linux-gnu.tar.gz"
[[unixODBC]]
arch = "x86_64"
git-tree-sha1 = "f712b446ae4464836e15fedcaf4bf942cd752952"
os = "macos"

    [[unixODBC.download]]
    sha256 = "74a94eacd37d052964090be4c80281b5b53765ba877df1a8594db6280bbbee15"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.x86_64-apple-darwin.tar.gz"
[[unixODBC]]
arch = "x86_64"
git-tree-sha1 = "84637f9dbc8f313838011977325eec613e7ca1bc"
libc = "glibc"
os = "linux"

    [[unixODBC.download]]
    sha256 = "96c31336042c7e78d7a7e9124d4cf27668813b879f8aab5c8efe7d53f3c2ddc7"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.x86_64-linux-gnu.tar.gz"
[[unixODBC]]
arch = "x86_64"
git-tree-sha1 = "09c06a374492abc98b8651ca62a408d2d20ac297"
libc = "musl"
os = "linux"

    [[unixODBC.download]]
    sha256 = "a6fd3505a9f00e40b72263c4d7980890f5ee62da32ee548c7a6c83ba86b7012e"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.x86_64-linux-musl.tar.gz"
[[unixODBC]]
arch = "x86_64"
git-tree-sha1 = "13090814dea92b6ad7c1da42121c592e51c792f5"
os = "freebsd"

    [[unixODBC.download]]
    sha256 = "ced30638382f8789667c5eb296d9d2c01595fe295e7da874ba0c4d617aed1c80"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.x86_64-unknown-freebsd.tar.gz"
[[unixODBC]]
arch = "x86_64"
git-tree-sha1 = "392b36df2971a7a0216aab618c06467ab557a093"
os = "windows"

    [[unixODBC.download]]
    sha256 = "d713c1e4a7a7975176f0b694e9f52753e58d620c763610767629260a609fc873"
    url = "https://github.com/JuliaBinaryWrappers/unixODBC_jll.jl/releases/download/unixODBC-v2.3.9+0/unixODBC.v2.3.9.x86_64-w64-mingw32.tar.gz"
